name: Deploy BILLION MARKETS WEB Production CI

on:
  push:
    branches: [main]

jobs:
  build-billion-market-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate .env
        run: |
          envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./.env.example > ./.env
        env:
          NEXT_PUBLIC_WEB_TITLE: Billion Markets
          NEXT_PUBLIC_WEB_DESCRIPTION: A platform to invest for future

          NEXT_PUBLIC_INTERNAL_API_URL: https://api.billionmarkets.com/api/v1
          NEXT_PUBLIC_API_URL: https://api.billionmarkets.com/api/v1
          NEXT_PUBLIC_WEB_MODE: production
          NEXT_PUBLIC_WEB_HOST_URL: https://billionmarkets.com
          NEXT_PUBLIC_STORAGE_URL: https://billionmarkets.com

          NEXT_PUBLIC_ENABLE_RBAC: true

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build the project
        run: yarn run build
        env:
          CI: false

      - name: Archive build artifacts
        run: tar -czf prod-billion-market-web.tar.gz .next public node_modules package.json yarn.lock Dockerfile.prod

      - name: Deploy Build Artifacts to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_PRIVATE_KEY }}
          source: prod-billion-market-web.tar.gz
          target: /home/quicksoft/prod-billion-market-web/

  deploy-billion-market-web-to-production:
    needs: build-billion-market-web
    runs-on: ubuntu-latest
    steps:
      - name: Deploy web to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/quicksoft/prod-billion-market-web/
            
            echo "Extracting build artifacts..."
            tar -xzf prod-billion-market-web.tar.gz
            rm prod-billion-market-web.tar.gz
            echo "Stopping existing container..."
            docker stop bm-web-prod || true
            docker rm bm-web-prod || true

            echo "Building the image..."
            docker build -t bm-web-prod:local -f /home/quicksoft/prod-billion-market-web/Dockerfile.prod .

            echo "starting server instance..."
            docker run -e NODE_ENV=production -d \
              --restart always \
              --network quicksoft_net1 \
              -p 2060:2060 \
              --name bm-web-prod \
              bm-web-prod:local

            docker builder prune -f
            docker image prune -f
            echo "Deploy Done...."